// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8EOauyMj5NSaaFc89E5HX8mwSW1ubwA',
    appId: '1:459490752567:web:929cf42f6adf0e5e77e7b2',
    messagingSenderId: '459490752567',
    projectId: 'auth-project-e3b75',
    authDomain: 'auth-project-e3b75.firebaseapp.com',
    storageBucket: 'auth-project-e3b75.appspot.com',
    measurementId: 'G-0K6CR4N4PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAEXkFB9SdEapLPnlxV4Xb9asyVTa8sYc',
    appId: '1:459490752567:android:04df9e9ef98b085d77e7b2',
    messagingSenderId: '459490752567',
    projectId: 'auth-project-e3b75',
    storageBucket: 'auth-project-e3b75.appspot.com',
  );
}
